module.exports = {
    applicationId: "7CCC0LXQFA",
    autocomplete: {
        apiKey: "OGVhMzZjOTU1Mjc2MWU3MjRkYjBjMTY1Y2E3NGVkOTdjNWQ1ZDJlMThlYWQ5NmQyM2JiM2NlMGIyY2EzOWI3N2ZpbHRlcnM9",
        displaySuggestionsCategories: false,
        enabled: true,
        nbOfCategoriesSuggestions: "1",
        nbOfProductsSuggestions: "3",
        nbOfQueriesSuggestions: "0",
        sections: [
            {
                hitsPerPage: "3",
                label: "Products",
                name: "products",
            },
            {            
                hitsPerPage: "1",
                label: "Categories",
                name: "categories",
            }
        ],
        templates: {},
        selector: ".algolia-search-input",
    },
    autofocus: true,
    baseUrl: "http://lansinohdev.brandshop.com",
    currencyCode: "USD",
    currencySymbol: "$",
    extensionVersion: "0.0.1",
    facets: [],
    hitsPerPage: 3,
    indexName: "magento_lansinoh",
    instant: {
        apiKey:"ZDJiZmYyNzZhYzcwYWY2OGEyY2IyMjNiYjJhOGViM2RhMjY2ZTZkZjIwNDc4MTFmYzRlY2JkZGQ3NjJhMzBhOGZpbHRlcnM9Jm51bWVyaWNGaWx0ZXJzPXZpc2liaWxpdHlfc2VhcmNoJTNEMQ==",
        content: "",
        description: "",
        enabled: false,
        hasFacets: false,
        imgHtml: "",
        isAddToCartEnabled: false,
        selector: ".main",
        showStaticContent: false,
        title: ""
    },
    isCategoryPage: false,
    isSearchPage: false,
    maxValuesPerFacet: 10,
    popularQueries: [],
    priceKey: ".USD.default",
    removeBranding: false,
    request: {
        formKey: "yfNTPMqj7ULqoIxc",
        path: "",
        query: "",
        refinementKey: "",
        refinementValue: "",
    },
    showCatsNotIncludedInNavigation: false,
    showSuggestionsOnNoResultsPage: true,
    sortingIndices: [],
    translations: {
        allDepartments: "All departments",
        categories: "Categories",
        clearAll: "Clear all",
        go: "Go",
        in: "in",
        nextPage: "Next page",
        noProducts: "No products for query",
        noResults: "No results",
        or: "or",
        orIn: "or in",
        popularQueries: "You can try one of the popular search queries",
        previousPage: "Previous page",
        products: "Products",
        refine: "Refine",
        relevance: "Relevance",
        searchBy: "Search by",
        searchFor: "Search for products",
        seeAll: "See all products",
        seeIn: "See products in",
        selectedFilters: "Selected Filters",
        to: "to"
    },
    urls: {
        logo: "http://lansinohdev.brandshop.com/skin/frontend/lansinoh/default/algoliasearch/algolia-logo.png"
    }
}